# Generated by Django 5.1.3 on 2024-11-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
